/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_InterWithNDK */

#ifndef _Included_jni_InterWithNDK
#define _Included_jni_InterWithNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_InterWithNDK
 * Method:    GetNDKString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_InterWithNDK_GetNDKString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
